name: Test Self Action

"on":
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/ci-self.yml"
      - "dist/*"
  schedule:
    # At 06:00 on Sunday.
    - cron: "0 6 * * 0"

permissions:
  contents: read

jobs:
  test-self-action:
    name: Make sure the action works on a clean machine without building
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: ./
        with:
          milliseconds: 1000
