---
name: CI

"on":
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - ".gitignore"
      - ".gitattributes"
      - ".yamllint"
      - "LICENSE"
      - "src/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
  schedule:
    # At 05:00 on Sunday.
    - cron: "0 5 * * 0"

permissions:
  contents: write

jobs:
  package:
    name: Run Everything and Package Distribution File
    runs-on: ubuntu-latest

    steps:
      - name: check out the codebase
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: set up python 3
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4
        with:
          python-version: "3.8"

      - name: setup node 16 and activate npm download cache
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16
          cache: "npm" # one of "npm", "yarn" or "pnpm"

      - name: setup/activate pre-commit cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}${{ hashFiles('**/.pre-commit-config.yaml') }}{% endraw %}

      # https://stackoverflow.com/a/69944063/13953427
      - name: install npm dependencies (including dev)
        run: npm ci -D

      - name: install dev dependencies
        run: pip3 install -r requirements-dev.txt

      # same order as in 'npm run all':
      - name: Compile Typescript.
        run: npm run build

      - name: Format Code.
        run: npm run format

      - name: Lint Code.
        run: npm run lint

      - name: Compile source into single file.
        run: npm run package

      - name: Test.
        run: npm run test

      - name: Upload coverage to Codecov and create Pull Request comment
        uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3

      - name: Commit generated dist.
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: "chore: generate packaged distribution file for {% raw %}${{ github.sha }}{% endraw %} \n {% raw %}${{ github.event.head_commit.message }}{% endraw %}"
          file_pattern: "dist/*"
