---
name: CI
permissions:
  contents: write
"on":
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - ".gitignore"
      - ".gitattributes"
      - ".yamllint"
      - "LICENSE"
      - "src/**"
      - "tests/**"
      - "dist/*"
      - "package.json"
      - "package-lock.json"
  schedule:
    # At 05:00 on Sunday.
    - cron: "0 5 * * 0"

jobs:
  package:
    name: Package Distribution File
    runs-on: ubuntu-latest

    steps:
      - name: check out the codebase
        uses: actions/checkout@v3

      - name: set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: setup/activate npm download cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: {% raw %}${{ hashFiles('package-lock.json') }}{% endraw %}

      - name: setup/activate pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}${{ hashFiles('**/.pre-commit-config.yaml') }}{% endraw %}

      - name: install npm dependencies
        run: npm install -D

      - name: install dev dependencies
        run: pip3 install -r requirements-dev.txt

      # same order as in 'npm run all':
      - name: Compile Typescript.
        run: npm run build

      - name: Format Code.
        run: npm run format

      - name: Lint Code.
        run: npm run lint

      - name: Compile source into single file.
        run: npm run package

      - name: Test.
        run: npm run test

      - name: Commit generated dist.
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: generate packaged distribution file for {% raw %}${{ github.sha }}{% endraw %} \n {% raw %}${{ github.event.head_commit.message }}{% endraw %}"
          file_pattern: "dist/*"

  test-self-action:
    name: Make sure the action works on a clean machine without building
    needs: package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          milliseconds: 1000
